### ISSUE TITLE
store and show instance icons

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-eduvpn-client#11]

**Comment by fkooman** [comment]
for "custom instance" you can use a placeholder icon.

**Comment by gijzelaerr** [comment]
instance logos are now shown in instance list.

**Comment by gijzelaerr** [comment]
@fkooman is there a default placeholder icon?

**Comment by fkooman** [comment]
I think the Android app uses the Let's Connect icon for that, i.e. https://github.com/eduvpn/android/blob/master/app/src/main/res/drawable-xxhdpi/external_provider.png but maybe @sveeke has a better idea?

**Comment by gijzelaerr** [comment]
for now I will just use the eduvpn logo, easy to adjust
