### ISSUE TITLE
theme the app more like the artwork

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-eduvpn-client#23]

**Comment by fkooman** [comment]
ideally everything would be contained in one window, and have no popups.

**Comment by gijzelaerr** [comment]
this is not true, for example the online accounts screen opens a new window. There is quite some inconsistency between different GTK guidelines.

**Comment by fkooman** [comment]
Actually it doesn't, I just checked. Of course it opens a window for the authorization stage. The UI is all part of the "Settings" window.

**Comment by gijzelaerr** [comment]
maybe we have different gnome versions

**Comment by fkooman** [comment]
![screenshot from 2017-09-01 16-51-17](https://user-images.githubusercontent.com/616885/29975204-d5fbce34-8f35-11e7-938c-903f366b023f.png)
![screenshot from 2017-09-01 16-51-27](https://user-images.githubusercontent.com/616885/29975205-d6372dc6-8f35-11e7-89b3-8f0a58b2222f.png)

**Comment by gijzelaerr** [comment]
![screen shot 2017-09-01 at 17 03 04](https://user-images.githubusercontent.com/326308/29975657-76a4f972-8f37-11e7-9aad-dddf9a66fbaa.png)

**Comment by fkooman** [comment]
And my GNOME version is already almost obsolete :)

**Comment by gijzelaerr** [comment]
added icons for institute and internet buttons

**Comment by gijzelaerr** [comment]
ok I think it looks like a proper mix between the app design and the gnome look.
