### ISSUE TITLE
show system messages when del/add/connect/disconnect

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-eduvpn-client#26]

**Comment by fkooman** [comment]
this would be visible as soon as the user tries to connect, al throughout the connection phase and during active connection.

**Comment by gijzelaerr** [comment]
looking into using libnotify for this.

**Comment by fkooman** [comment]
why? just fetch the messages before connecting and keep them visible...

**Comment by gijzelaerr** [comment]
I don't know what you are talking about. I'm going to sue libnotify to show messages to the user in the notification area.

**Comment by fkooman** [comment]
Ah! Yes, now I get it. Sorry!

**Comment by gijzelaerr** [comment]
basic notification is working in the master, could use improvements like logo etc.
