### ISSUE TITLE
dependency on networkmanager/openvpn missing

### ISSUE THREAD

**Issue by fkooman** [gijzelaerr/python-eduvpn-client#5]
at least on `network-manager-openvpn-gnome`

**Comment by fkooman** [comment]
okay, technically maybe not the gnome part, but for sure the openvpn part :)

**Comment by gijzelaerr** [comment]
this is actually a packaging issue. fixed in 0.3-2 https://github.com/eduvpn-debian/python-eduvpn-client/commit/6030ae607ea9ed1d65687744c661350a623cb353
